### PR TITLE
Electron 10

### LINKED ISSUE #1: Node JS Version
Hi,
great job!
What version of NodeJS are you using? I always get an error that it requires another node version and that I should try and recompile.

Thanks!

### PR DESCRIPTION
**Pull request by hrueger**
fixes #1 

Can someone check if that works on MacOS, too?

### CODE REVIEW

**Comment by kurdin** [comment]
@hrueger  on Mac I have error
```App threw an error during load
Error: The module '/Users/xxx/projects/tmp/tmp/obs-studio-node-example/node_modules/node-window-rendering/node_window_rendering.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 82. Please try re-compiling or re-installing
```
for mac in package.json I use
    "node-window-rendering": "https://slobs-node-window-rendering.s3-us-west-2.amazonaws.com/node-window-rendering-1.0.12-osx.tar.gz",

seems like `node-window-rendering` release does not support Electron 10 yet

**Comment by hrueger** [comment]
@kurdin is that the latest version of `node-window-rendering`?

You can find the latest version by cloning https://github.com/stream-labs/streamlabs-obs, running `npm i` and having a look at the output.

**Comment by hrueger** [comment]
@alse @chfeizy you seem to have a Mac, too. Could you check if this PR is working for you?

**Comment by Envek** [comment]
@hrueger I'm super excited to get fresh Electron version (with modern JS goodies)! Thank you very much!

However I had no time to review it yet, sorry. I will try to get to it in a couple of days.

**Comment by Envek** [comment]
Thank you very much for update! 🙏 

If someone will have problems on MacOS, let them create new issue for it.

**Comment by psd-coder** [comment]
@hrueger Hi! I have the same result as @kurdin on Mac. And mentioned version of `node-window-rendering` is the latest from the `obs-studio-node` repository.

**Comment by hrueger** [comment]
@psd-coder Hm. Can you please create a new issue for that?

**Comment by hrueger** [comment]
@Envek I got the info that `osn` now works with Electron 10 from [this comment](https://github.com/stream-labs/obs-studio-node/issues/605#issuecomment-701736896) but it seems like `streamlabs-obs` is [still using Electron 6](https://github.com/stream-labs/streamlabs-obs/blob/ba79de055a0bf6727d3f56d75590a65e48ac7827/package.json#L136)...

**Pull request merged**
