### PR TITLE
added virtual camera controls

### PR DESCRIPTION
**Pull request by hrueger**
Hi,
while recently digging through Streamlabs OBS's code, I found some methods for controlling the virtual camera plugin. It is quite easy to use.
This PR adds control buttons for installing the plugin, starting and stopping the camera as well as uninstalling it.
grafik

### CODE REVIEW

**Comment by Envek** [comment]
Whoa! Thank you! I will take a look a bit later this week.

**Review by Envek — CHANGES_REQUESTED** [review]
Can you please add some instructions into README?
I tried to run it locally and didn't get what should I after I installed plugin and started camera. Should I go to Windows control panel to set virtual webcam up or open OBS?

**Comment by hrueger** [comment]
Hm, for me it basically works out of the box. I clicked the "install" button and have to input my admin password twice. Then I click start and the camera shows up, for example in Zoom.

However, the camera is labeled "Streamlabs OBS Virtual Camera". Maybe some registration has already been done by Streamlabs OBS from my testing?

I'll check tomorrow.

**Comment by Envek** [comment]
Oh, yes, now I can see my screen as picture from "Streamlabs OBS Virtual Camera" in other apps.

Just please add a section to README with that.

**Comment by hrueger** [comment]
OK, I will. Do you have any idea why it shows up as `Streamlabs OBS Virtual Camera`? The relevant code in `obs-studio-node` is [here](https://github.com/stream-labs/obs-studio-node/blob/36eeb480f36c9c414fb73223d144f4889e331029/obs-studio-client/source/nodeobs_service.cpp#L276), however, there's no hardcoded `Streamlabs OBS Virtual Camera`...

**Review by Envek — APPROVED** [review]
Thanks!

**Pull request merged**
